VentaMenu/config/routes.rb
Rails.application.routes.draw do

  
  
  resources :orders

  resources :contacts

  resources :customers

  get 'select_menu/index'
  get 'cus_local/index'
  get 'cus_local/localmenu'
  get 'cus_local/menuseleccionado'
  get 'nosotros/index'
  
  resources :menu_details

  resources :menus

  resources :foods

  resources :type_foods

  resources :type_menus

  resources :locals

  resources :cities
  
  resources :contats

  devise_for :admins
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  
  root 'home#index'

end

VentaMenu/app/models/admin.rb
# == Schema Information
#
# Table name: admins
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

VentaMenu/app/models/city.rb
# == Schema Information
#
# Table name: cities
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

class City < ActiveRecord::Base
    has_many :locals
end

VentaMenu/app/models/contact.rb
class Contact < ActiveRecord::Base
end

VentaMenu/app/models/customer.rb
class Customer < ActiveRecord::Base
end

VentaMenu/app/models/food.rb
# == Schema Information
#
# Table name: foods
#
#  id                   :integer          not null, primary key
#  name                 :string(255)
#  description          :string(255)
#  type_food_id         :integer
#  created_at           :datetime
#  updated_at           :datetime
#  picture_file_name    :string(255)
#  picture_content_type :string(255)
#  picture_file_size    :integer
#  picture_updated_at   :datetime
#

class Food < ActiveRecord::Base
    belongs_to :type_food
    
 #Attachment attribute
  has_attached_file :picture, 
                    styles: {medium: "300x300>", thumb: "100x100>"},
                    default_url: "/images/:styles/missing.png"
 validates :picture, 
 attachment_presence: true, presence: true
 validates_attachment :picture, 
 content_type: { content_type: ["image/jpeg", "image/png", "image/gif"] }

end

VentaMenu/app/models/local.rb
# == Schema Information
#
# Table name: locals
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  address    :string(255)
#  telephone  :string(255)
#  celphone   :string(255)
#  mail       :string(255)
#  city_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Local < ActiveRecord::Base
  belongs_to :city
end

VentaMenu/app/models/menu.rb
# == Schema Information
#
# Table name: menus
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  dateMenu   :date
#  status     :string(255)
#  price      :float(24)
#  local_id   :integer
#  created_at :datetime
#  updated_at :datetime
#

class Menu < ActiveRecord::Base
  belongs_to :local
end

VentaMenu/app/models/menu_detail.rb
# == Schema Information
#
# Table name: menu_details
#
#  id           :integer          not null, primary key
#  status       :string(255)
#  menu_id      :integer
#  food_id      :integer
#  type_menu_id :integer
#  created_at   :datetime
#  updated_at   :datetime
#

class MenuDetail < ActiveRecord::Base
  belongs_to :menu
  belongs_to :food
  belongs_to :type_menu
end

VentaMenu/app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :customer
  belongs_to :menu
end

VentaMenu/app/models/type_food.rb
# == Schema Information
#
# Table name: type_foods
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class TypeFood < ActiveRecord::Base
  has_many :foods
end

VentaMenu/app/models/type_menu.rb
# == Schema Information
#
# Table name: type_menus
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class TypeMenu < ActiveRecord::Base
    has_many :menu_details
end

VentaMenu/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  admin                  :boolean          default(FALSE), not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

VentaMenu/app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @customers = Customer.all
    respond_with(@customers)
  end

  def show
    respond_with(@customer)
  end

  def new
    @customer = Customer.new
    respond_with(@customer)
  end

  def edit
  end

  def create
    
    @customer = Customer.new(customer_params)
    @customer.save
    #@menu_details.each do |menud| 
    #  cliente=@customer
    #  Order.customer=cliente
    # Order.menu=menud.menu
    #  Order.save
    #end
    respond_with(@customer)
  end

  def update
    @customer.update(customer_params)
    respond_with(@customer)
  end

  def destroy
    @customer.destroy
    respond_with(@customer)
  end

  private
    def set_customer
      @customer = Customer.find(params[:id])
    end

    def customer_params
      params.require(:customer).permit(:name, :lastname, :celphone, :mail, :address)
    end
end

VentaMenu/app/helpers/cities_helper.rb
module CitiesHelper
end

VentaMenu/app/helpers/contacts_helper.rb
module ContactsHelper
end

VentaMenu/app/helpers/cus_local_helper.rb
module CusLocalHelper
end

VentaMenu/app/helpers/customers_helper.rb
module CustomersHelper
end

VentaMenu/app/helpers/foods_helper.rb
module FoodsHelper
end

VentaMenu/app/helpers/home_helper.rb
module HomeHelper
end

VentaMenu/app/helpers/locals_helper.rb
module LocalsHelper
end

VentaMenu/app/helpers/menus_helper.rb
module MenusHelper
end

VentaMenu/app/helpers/nosotros_helper.rb
module NosotrosHelper
end

VentaMenu/app/helpers/orders_helper.rb
module OrdersHelper
end

VentaMenu/app/views/customers/_form.html.erb
<%= simple_form_for @customer, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= error_span(@customer[:name]) %>
  <%= f.input :lastname %>
  <%= error_span(@customer[:lastname]) %>
  <%= f.input :celphone %>
  <%= error_span(@customer[:celphone]) %>
  <%= f.input :mail %>
  <%= error_span(@customer[:mail]) %>
  <%= f.input :address %>
  <%= error_span(@customer[:address]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                customers_path, :class => 'btn btn-default' %>
<% end %>

VentaMenu/app/views/customers/edit.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

VentaMenu/app/views/customers/index.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:lastname) %></th>
      <th><%= model_class.human_attribute_name(:celphone) %></th>
      <th><%= model_class.human_attribute_name(:mail) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= link_to customer.id, customer_path(customer) %></td>
        <td><%= customer.name %></td>
        <td><%= customer.lastname %></td>
        <td><%= customer.celphone %></td>
        <td><%= customer.mail %></td>
        <td><%= customer.address %></td>
        <td><%=l customer.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_customer_path(customer), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      customer_path(customer),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_customer_path,
            :class => 'btn btn-primary' %>

VentaMenu/app/views/customers/new.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

VentaMenu/app/views/customers/show.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @customer.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:lastname) %>:</strong></dt>
  <dd><%= @customer.lastname %></dd>
  <dt><strong><%= model_class.human_attribute_name(:celphone) %>:</strong></dt>
  <dd><%= @customer.celphone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:mail) %>:</strong></dt>
  <dd><%= @customer.mail %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @customer.address %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              customers_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_customer_path(@customer), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              customer_path(@customer),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>